- name: retreive IP
  ipify_facts:

- name: associate IP to DNS
  ovh_dns:
    endpoint: "ovh-eu"
    application_key: "{{ ovh_application_key }}"
    application_secret: "{{ ovh_application_secret }}"
    consumer_key: "{{ ovh_consumer_key }}"
    domain: "{{ forge_domain }}"
    name: "{{ forge_subdomain }}"
    type: "A"
    value: "{{ ipify_public_ip }}"
    state: present
  delegate_to: localhost

- name: install packages
  yay:
    name: "python-passlib"
    state: present

- name: update password
  user:
    name="{{ forge_user }}"
    update_password="always"
    password="{{ forge_password | password_hash('sha512') }}"
