- name: retreive IP
  ipify_facts:

- name: associate IP to DNS
  ovh:
    endpoint: "ovh-eu"
    application_key: "{{ ovh_application_key }}"
    application_secret: "{{ ovh_application_secret }}"
    consumer_key: "{{ ovh_consumer_key }}"
    service: dns
    domain: "{{ forge_domain }}"
    ip: "{{ ipify_public_ip }}"
    name: "{{ forge_subdomain }}"
