---
- name: delete old working directory
  file:
    path: "/tmp/forge"
    state: absent
  changed_when: false

- name: create working directory
  file:
    path: "/tmp/forge"
    state: directory
  changed_when: false

- name: clone git repo
  git:
    repo: "https://github.com/radium226/forge.git"
    version: "arch-package"
    dest: "/tmp/forge"

- name: make package
  shell: |
    cd "/tmp/forge"
    makepkg \
      --force \
      --syncdeps \
      --skipchecksums \
      --noconfirm \
      --clean \
      --cleanbuild

- name: install packages
  shell: |
    find "/tmp/forge" -name "*.pkg.tar.xz" -exec yay -U "{}" --noconfirm \;
